---
apiVersion: v1
kind: ConfigMap
metadata:
  name: golden-snitch-nginx-conf
data:
  nginx.conf: |
    worker_processes  1;

    # error_log /var/log/nginx/error.log;
    error_log /dev/stdout info;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 8080 ssl http2;
            ssl_certificate     /etc/tls/private/tls.crt;
            ssl_certificate_key /etc/tls/private/tls.key;

            access_log /var/log/nginx/access.log;
            proxy_temp_path /tmp/proxy_temp;

            # This will make sure that any changes to the lua code file is picked up
            # without reloading or restarting nginx
            lua_code_cache off;

            location / {
                proxy_pass https://{{ .Values.proxyPass }}.{{ .Values.namespace }}.svc;
                log_by_lua_file lua/request_logger.lua;
            }
        }
    }
---