{{- if .Values.dockerHubAcc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerHubAcc.name | default "docker-hub" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "secret.dockercfg" . }}
{{- end -}}